### ISSUE TITLE
Worth keeping the stalekey engine in core

### ISSUE THREAD

**Issue by max-arnold** [saltstack/great-module-migration#11]
The `stalekey` engine might be suitable in the core

**Comment by doesitblend** [comment]
I disagree as this can be replaced by a Thorium reactor these and is the documented example for the Thorium reactor engine. But I can understand that a lot of users have used this.

**Comment by dwoz** [comment]
I can get behind this.

@twangboy @dmurphy18 @whytewolf @s0undt3ch

**Comment by whytewolf** [comment]
I don't see a problem with keeping it around. it hasn't been touched in 3 years anyway. and is one of the few things that has almost no bugs listed in the salt issue. but is a widely used engine.

**Comment by s0undt3ch** [comment]
I'm good with keeping it

**Comment by dmurphy18** [comment]
keep it

**Comment by twangboy** [comment]
I'm good with keeping it
